# Generated by Django 3.2.4 on 2021-06-21 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fst', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fst.basemodel')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('player', models.CharField(max_length=128, verbose_name='player')),
                ('max_vitality', models.SmallIntegerField(verbose_name='max_vitality')),
                ('current_vitality', models.SmallIntegerField(verbose_name='current_vitality')),
                ('max_wyrd', models.SmallIntegerField(verbose_name='max_wyrd')),
                ('current_wyrd', models.SmallIntegerField(verbose_name='current_wyrd')),
                ('rank', models.CharField(blank=True, max_length=128, verbose_name='rank')),
                ('allies', models.CharField(blank=True, max_length=512, verbose_name='alies')),
                ('stigma', models.CharField(blank=True, max_length=128, verbose_name='stigma')),
                ('race', models.CharField(blank=True, max_length=128, verbose_name='race')),
                ('age', models.SmallIntegerField(verbose_name='age')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], max_length=1, verbose_name='gender')),
                ('home_planet', models.CharField(blank=True, max_length=128, verbose_name='home_planet')),
                ('hair', models.CharField(blank=True, max_length=128, verbose_name='hair')),
                ('eyes', models.CharField(blank=True, max_length=128, verbose_name='eyes')),
                ('complexion', models.CharField(blank=True, max_length=128, verbose_name='complexion')),
                ('height', models.CharField(blank=True, max_length=128, verbose_name='height')),
                ('weight', models.CharField(blank=True, max_length=128, verbose_name='weight')),
                ('image', models.TextField(verbose_name='image')),
                ('history', models.TextField(verbose_name='history')),
                ('experience_points', models.SmallIntegerField(verbose_name='experience_points')),
                ('current_hits', models.SmallIntegerField(verbose_name='current_hits')),
                ('wip', models.BooleanField(default=True, verbose_name='wip')),
            ],
            options={
                'verbose_name': 'character',
                'verbose_name_plural': 'characters',
            },
            bases=('fst.basemodel',),
        ),
    ]
